<a href="https://colab.research.google.com/github/sarthakjaiswal999/healthcare-fraud-detection-sql-project/blob/main/Healthcare_Claims_Analytics_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install duckdb pandas

Requirement already satisfied: duckdb in /usr/local/lib/python3.12/dist-packages (1.3.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd
import duckdb

In [4]:
df = pd.read_csv("/content/drive/MyDrive/Healthcare Project/synthetic_health_claims.csv")
df.head()

,Patient_ID,Policy_Number,Claim_ID,Claim_Date,Service_Date,Policy_Expiration_Date,Claim_Amount,Patient_Age,Patient_Gender,Patient_City,...,Discharge_Type,Length_of_Stay_Days,Service_Type,Deductible_Amount,CoPay_Amount,Number_of_Previous_Claims_Patient,Number_of_Previous_Claims_Provider,Provider_Patient_Distance_Miles,Claim_Submitted_Late,Is_Fraudulent
0,67349080,XAI956194550,18874,2021-06-16,2021-05-01,2024-11-20,462337.48,28,Female,Houston,...,Rehab/Skilled Nursing,47,Inpatient,3440.06,824.59,0,16,939.08,True,False
1,85973291,XAI215993963,8762,2025-01-19,2025-01-17,2029-04-07,1883481.30,40,Other,Washington,...,Deceased,0,Outpatient,3618.40,851.43,0,6,170.40,False,True
2,62454860,XAI146653263,1920,2023-05-05,2023-03-24,2024-09-04,1500658.89,90,Female,Seattle,...,Deceased,0,Pharmacy,2442.41,616.23,0,2,549.38,True,False
3,58632240,XAI216596381,1316,2021-11-07,2021-11-02,2025-12-24,572237.61,49,Other,Fort Worth,...,Deceased,0,Pharmacy,587.78,459.33,0,2,396.49,False,True
4,96347311,XAI056900359,17039,2024-03-25,2024-02-18,2028-07-30,2088293.84,24,Female,New York,...,Deceased,0,Emergency Room,3047.55,847.40,0,15,865.87,True,False

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20100 entries, 0 to 20099
Data columns (total 30 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Patient_ID                          20100 non-null  int64
 1   Policy_Number                       20100 non-null  object
 2   Claim_ID                            20100 non-null  int64
 3   Claim_Date                          20100 non-null  object
 4   Service_Date                        20100 non-null  object
 5   Policy_Expiration_Date              20100 non-null  object
 6   Claim_Amount                        20100 non-null  float64
 7   Patient_Age                         20100 non-null  int64
 8   Patient_Gender                      20100 non-null  object
 9   Patient_City                        20100 non-null  object
 10  Patient_State                       20100 non-null  object
 11  Hospital_ID                         20100 non-null  int64
 12  Provider_Type                       20100 non-null  object
 13  Provider_Specialty                  20100 non-null  object
 14  Provider_City                       20100 non-null  object
 15  Provider_State                      20100 non-null  object
 16  Diagnosis_Code                      20100 non-null  object
 17  Procedure_Code                      20100 non-null  int64
 18  Number_of_Procedures                20100 non-null  int64
 19  Admission_Type                      20100 non-null  object
 20  Discharge_Type                      20100 non-null  object
 21  Length_of_Stay_Days                 20100 non-null  int64
 22  Service_Type                        20100 non-null  object
 23  Deductible_Amount                   20100 non-null  float64
 24  CoPay_Amount                        20100 non-null  float64
 25  Number_of_Previous_Claims_Patient   20100 non-null  int64
 26  Number_of_Previous_Claims_Provider  20100 non-null  int64
 27  Provider_Patient_Distance_Miles     20100 non-null  float64
 28  Claim_Submitted_Late                20100 non-null  bool
 29  Is_Fraudulent                       20100 non-null  bool
dtypes: bool(2), float64(4), int64(9), object(15)
memory usage: 4.3+ MB

In [6]:
df.describe()

,Patient_ID,Claim_ID,Claim_Amount,Patient_Age,Hospital_ID,Procedure_Code,Number_of_Procedures,Length_of_Stay_Days,Deductible_Amount,CoPay_Amount,Number_of_Previous_Claims_Patient,Number_of_Previous_Claims_Provider,Provider_Patient_Distance_Miles
count,2.010000e+04,20100.000000,2.010000e+04,20100.000000,20100.000000,20100.000000,20100.000000,20100.000000,20100.000000,20100.000000,20100.000000,20100.000000,20100.000000
mean,5.528158e+07,10005.580348,1.245349e+06,45.104925,500.204179,92463.849851,5.510249,4.975821,2508.487758,499.665796,0.000299,10.027910,499.480532
std,2.606038e+07,5774.135663,6.983001e+05,26.300942,288.437500,8151.470654,2.882847,13.239804,1443.579069,288.397727,0.017275,6.622332,289.745360
min,1.000265e+07,1.000000,5.516780e+03,0.000000,1.000000,71045.000000,1.000000,0.000000,0.030000,0.020000,0.000000,0.000000,0.020000
25%,3.266819e+07,5005.750000,6.674103e+05,22.000000,251.000000,93040.000000,3.000000,0.000000,1251.440000,248.800000,0.000000,5.000000,246.380000
50%,5.551009e+07,10008.500000,1.221707e+06,45.000000,500.000000,93571.000000,6.000000,0.000000,2508.875000,499.950000,0.000000,10.000000,498.410000
75%,7.814105e+07,15011.250000,1.835603e+06,68.000000,752.000000,99204.000000,8.000000,0.000000,3755.080000,750.040000,0.000000,15.000000,751.000000
max,9.998440e+07,20000.000000,2.499689e+06,90.000000,1000.000000,99284.000000,10.000000,60.000000,4999.870000,999.880000,1.000000,34.000000,999.980000

In [7]:
df.columns

Index(['Patient_ID', 'Policy_Number', 'Claim_ID', 'Claim_Date', 'Service_Date',
       'Policy_Expiration_Date', 'Claim_Amount', 'Patient_Age',
       'Patient_Gender', 'Patient_City', 'Patient_State', 'Hospital_ID',
       'Provider_Type', 'Provider_Specialty', 'Provider_City',
       'Provider_State', 'Diagnosis_Code', 'Procedure_Code',
       'Number_of_Procedures', 'Admission_Type', 'Discharge_Type',
       'Length_of_Stay_Days', 'Service_Type', 'Deductible_Amount',
       'CoPay_Amount', 'Number_of_Previous_Claims_Patient',
       'Number_of_Previous_Claims_Provider', 'Provider_Patient_Distance_Miles',
       'Claim_Submitted_Late', 'Is_Fraudulent'],
      dtype='object')

In [8]:
df.info()
df.describe()
df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20100 entries, 0 to 20099
Data columns (total 30 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Patient_ID                          20100 non-null  int64
 1   Policy_Number                       20100 non-null  object
 2   Claim_ID                            20100 non-null  int64
 3   Claim_Date                          20100 non-null  object
 4   Service_Date                        20100 non-null  object
 5   Policy_Expiration_Date              20100 non-null  object
 6   Claim_Amount                        20100 non-null  float64
 7   Patient_Age                         20100 non-null  int64
 8   Patient_Gender                      20100 non-null  object
 9   Patient_City                        20100 non-null  object
 10  Patient_State                       20100 non-null  object
 11  Hospital_ID                         20100 non-null  int64
 12  Provider_Type                       20100 non-null  object
 13  Provider_Specialty                  20100 non-null  object
 14  Provider_City                       20100 non-null  object
 15  Provider_State                      20100 non-null  object
 16  Diagnosis_Code                      20100 non-null  object
 17  Procedure_Code                      20100 non-null  int64
 18  Number_of_Procedures                20100 non-null  int64
 19  Admission_Type                      20100 non-null  object
 20  Discharge_Type                      20100 non-null  object
 21  Length_of_Stay_Days                 20100 non-null  int64
 22  Service_Type                        20100 non-null  object
 23  Deductible_Amount                   20100 non-null  float64
 24  CoPay_Amount                        20100 non-null  float64
 25  Number_of_Previous_Claims_Patient   20100 non-null  int64
 26  Number_of_Previous_Claims_Provider  20100 non-null  int64
 27  Provider_Patient_Distance_Miles     20100 non-null  float64
 28  Claim_Submitted_Late                20100 non-null  bool
 29  Is_Fraudulent                       20100 non-null  bool
dtypes: bool(2), float64(4), int64(9), object(15)
memory usage: 4.3+ MB

Index(['Patient_ID', 'Policy_Number', 'Claim_ID', 'Claim_Date', 'Service_Date',
       'Policy_Expiration_Date', 'Claim_Amount', 'Patient_Age',
       'Patient_Gender', 'Patient_City', 'Patient_State', 'Hospital_ID',
       'Provider_Type', 'Provider_Specialty', 'Provider_City',
       'Provider_State', 'Diagnosis_Code', 'Procedure_Code',
       'Number_of_Procedures', 'Admission_Type', 'Discharge_Type',
       'Length_of_Stay_Days', 'Service_Type', 'Deductible_Amount',
       'CoPay_Amount', 'Number_of_Previous_Claims_Patient',
       'Number_of_Previous_Claims_Provider', 'Provider_Patient_Distance_Miles',
       'Claim_Submitted_Late', 'Is_Fraudulent'],
      dtype='object')

In [9]:
import duckdb

In [10]:
con = duckdb.connect()

In [11]:
con.register("claims", df)

In [12]:
con.execute("""

SELECT
    Provider_Specialty,

    COUNT(*) AS total_claims,

    ROUND(SUM(Claim_Amount), 2) AS total_claim_amount,

    ROUND(AVG(Claim_Amount), 2) AS avg_claim_amount

FROM claims

GROUP BY Provider_Specialty

ORDER BY total_claim_amount DESC

LIMIT 10

""").fetchdf()

  Provider_Specialty  total_claims  total_claim_amount  avg_claim_amount
0         Cardiology          2797        3.297224e+09        1178842.89
1        Orthopedics          2714        3.181778e+09        1172357.49
2          Radiology          1893        2.389372e+09        1262214.34
3        Dermatology          1833        2.363475e+09        1289402.78
4   Physical Therapy          1845        2.358083e+09        1278093.73
5          Neurology          1867        2.316584e+09        1240805.44
6           Oncology          1819        2.313194e+09        1271684.18
7         Psychiatry          1794        2.301301e+09        1282776.27
8   General Practice          1765        2.266244e+09        1283991.02
9         Pediatrics          1773        2.244262e+09        1265799.06

In [13]:
con.execute("""

SELECT

    Provider_Specialty,

    COUNT(*) AS total_claims,

    SUM(
        CASE
            WHEN Is_Fraudulent = TRUE THEN 1
            ELSE 0
        END
    ) AS fraudulent_claims,

    ROUND(
        (
            SUM(
                CASE
                    WHEN Is_Fraudulent = TRUE THEN 1
                    ELSE 0
                END
            ) * 100.0
        ) / COUNT(*),
        2
    ) AS fraud_percentage

FROM claims

GROUP BY Provider_Specialty

ORDER BY fraud_percentage DESC

LIMIT 10

""").fetchdf()

  Provider_Specialty  total_claims  fraudulent_claims  fraud_percentage
0         Cardiology          2797             1302.0             46.55
1        Orthopedics          2714             1239.0             45.65
2   General Practice          1765              314.0             17.79
3         Pediatrics          1773              311.0             17.54
4   Physical Therapy          1845              320.0             17.34
5          Neurology          1867              317.0             16.98
6         Psychiatry          1794              301.0             16.78
7           Oncology          1819              305.0             16.77
8          Radiology          1893              306.0             16.16
9        Dermatology          1833              296.0             16.15

In [14]:
con.execute("""

SELECT
    Claim_Submitted_Late,

    COUNT(*) AS total_claims,

    SUM(
        CASE
            WHEN Is_Fraudulent = TRUE THEN 1
            ELSE 0
        END
    ) AS fraudulent_claims,

    ROUND(
        SUM(
            CASE
                WHEN Is_Fraudulent = TRUE THEN 1
                ELSE 0
            END
        ) * 100.0 / COUNT(*),
        2
    ) AS fraud_percentage

FROM claims

GROUP BY Claim_Submitted_Late

""").fetchdf()

   Claim_Submitted_Late  total_claims  fraudulent_claims  fraud_percentage
0                 False          6894             1655.0             24.01
1                  True         13206             3356.0             25.41

In [15]:
con.execute("""

SELECT
    Provider_Specialty,

    COUNT(*) AS total_claims,

    SUM(
        CASE
            WHEN Is_Fraudulent = TRUE THEN 1
            ELSE 0
        END
    ) AS fraudulent_claims,

    ROUND(
        SUM(
            CASE
                WHEN Is_Fraudulent = TRUE THEN 1
                ELSE 0
            END
        ) * 100.0 / COUNT(*),
        2
    ) AS fraud_percentage

FROM claims

GROUP BY Provider_Specialty

ORDER BY fraud_percentage DESC

LIMIT 10

""").fetchdf()

  Provider_Specialty  total_claims  fraudulent_claims  fraud_percentage
0         Cardiology          2797             1302.0             46.55
1        Orthopedics          2714             1239.0             45.65
2   General Practice          1765              314.0             17.79
3         Pediatrics          1773              311.0             17.54
4   Physical Therapy          1845              320.0             17.34
5          Neurology          1867              317.0             16.98
6         Psychiatry          1794              301.0             16.78
7           Oncology          1819              305.0             16.77
8          Radiology          1893              306.0             16.16
9        Dermatology          1833              296.0             16.15

In [16]:
con.execute("""

SELECT

    CASE
        WHEN Number_of_Previous_Claims_Patient <= 2 THEN 'Low'
        WHEN Number_of_Previous_Claims_Patient <= 6 THEN 'Medium'
        ELSE 'High'
    END AS claim_history_bucket,

    COUNT(*) AS total_claims,

    SUM(
        CASE
            WHEN Is_Fraudulent = TRUE THEN 1
            ELSE 0
        END
    ) AS fraudulent_claims,

    ROUND(
        SUM(
            CASE
                WHEN Is_Fraudulent = TRUE THEN 1
                ELSE 0
            END
        ) * 100.0 / COUNT(*),
        2
    ) AS fraud_percentage

FROM claims

GROUP BY claim_history_bucket

ORDER BY fraud_percentage DESC

""").fetchdf()

  claim_history_bucket  total_claims  fraudulent_claims  fraud_percentage
0                  Low         20100             5011.0             24.93

In [17]:
con.execute("""

SELECT
    MIN(Number_of_Previous_Claims_Patient) AS min_claims,
    MAX(Number_of_Previous_Claims_Patient) AS max_claims,
    AVG(Number_of_Previous_Claims_Patient) AS avg_claims

FROM claims

""").fetchdf()

   min_claims  max_claims  avg_claims
0           0           1    0.000299

In [18]:
con.execute("""

SELECT
    MIN(Length_of_Stay_Days) AS mindays,
    MAX(Length_of_Stay_Days) AS masxday,
    AVG(Length_of_Stay_Days) AS avgdays

FROM claims

""").fetchdf()

   mindays  masxday   avgdays
0        0       60  4.975821

In [19]:
con.execute("""

SELECT

    CASE
        WHEN Length_of_Stay_Days <= 3 THEN 'Short Stay'

        WHEN Length_of_Stay_Days <= 10 THEN 'Medium Stay'

        ELSE 'Long Stay'

    END AS stay_bucket,

    COUNT(*) AS total_claims,

    SUM(
        CASE
            WHEN Is_Fraudulent = TRUE THEN 1
            ELSE 0
        END
    ) AS fraudulent_claims,

    ROUND(
        SUM(
            CASE
                WHEN Is_Fraudulent = TRUE THEN 1
                ELSE 0
            END
        ) * 100.0 / COUNT(*),
        2
    ) AS fraud_percentage

FROM claims

GROUP BY stay_bucket

ORDER BY fraud_percentage DESC

""").fetchdf()

   stay_bucket  total_claims  fraudulent_claims  fraud_percentage
0   Short Stay         16988             4579.0             26.95
1    Long Stay          2727              380.0             13.93
2  Medium Stay           385               52.0             13.51

In [20]:
con.execute("""

SELECT

    Provider_Specialty,

    CASE
        WHEN Length_of_Stay_Days <= 3 THEN 'Short Stay'

        WHEN Length_of_Stay_Days <= 10 THEN 'Medium Stay'

        ELSE 'Long Stay'

    END AS stay_bucket,

    COUNT(*) AS total_claims,

    SUM(
        CASE
            WHEN Is_Fraudulent = TRUE THEN 1
            ELSE 0
        END
    ) AS fraudulent_claims,

    ROUND(
        SUM(
            CASE
                WHEN Is_Fraudulent = TRUE THEN 1
                ELSE 0
            END
        ) * 100.0 / COUNT(*),
        2
    ) AS fraud_percentage

FROM claims

GROUP BY Provider_Specialty, stay_bucket

ORDER BY fraud_percentage DESC

LIMIT 15

""").fetchdf()

,Provider_Specialty,stay_bucket,total_claims,fraudulent_claims,fraud_percentage
0,Cardiology,Short Stay,2496,1270.0,50.88
1,Orthopedics,Short Stay,2421,1200.0,49.57
2,General Practice,Medium Stay,38,8.0,21.05
3,General Practice,Short Stay,1438,264.0,18.36
4,Pediatrics,Short Stay,1490,270.0,18.12
5,Neurology,Short Stay,1533,275.0,17.94
6,Physical Therapy,Short Stay,1553,276.0,17.77
7,Oncology,Short Stay,1508,262.0,17.37
8,Psychiatry,Short Stay,1450,250.0,17.24
9,Dermatology,Short Stay,1513,254.0,16.79
10,Radiology,Long Stay,255,42.0,16.47
11,Psychiatry,Medium Stay,43,7.0,16.28
12,Radiology,Short Stay,1586,258.0,16.27
13,Physical Therapy,Medium Stay,25,4.0,16.00
14,Physical Therapy,Long Stay,267,40.0,14.98

In [21]:
  con.execute("""

  WITH specialty_claims AS (

      SELECT
          Provider_Specialty,

          SUM(Claim_Amount) AS total_claim_amount

      FROM claims

      GROUP BY Provider_Specialty

  )

  SELECT

      Provider_Specialty,

      ROUND(total_claim_amount, 2) AS total_claim_amount,

      RANK() OVER(
          ORDER BY total_claim_amount DESC
      ) AS specialty_rank

  FROM specialty_claims

  ORDER BY specialty_rank

  """).fetchdf()

  Provider_Specialty  total_claim_amount  specialty_rank
0         Cardiology        3.297224e+09               1
1        Orthopedics        3.181778e+09               2
2          Radiology        2.389372e+09               3
3        Dermatology        2.363475e+09               4
4   Physical Therapy        2.358083e+09               5
5          Neurology        2.316584e+09               6
6           Oncology        2.313194e+09               7
7         Psychiatry        2.301301e+09               8
8   General Practice        2.266244e+09               9
9         Pediatrics        2.244262e+09              10

In [22]:
con.execute("""

WITH fraud_summary AS (

    SELECT

        Provider_Specialty,

        CASE
            WHEN Length_of_Stay_Days <= 3 THEN 'Short Stay'
            WHEN Length_of_Stay_Days <= 10 THEN 'Medium Stay'
            ELSE 'Long Stay'
        END AS stay_bucket,

        COUNT(*) AS total_claims,

        SUM(
            CASE
                WHEN Is_Fraudulent = TRUE THEN 1
                ELSE 0
            END
        ) AS fraudulent_claims,

        ROUND(
            SUM(
                CASE
                    WHEN Is_Fraudulent = TRUE THEN 1
                    ELSE 0
                END
            ) * 100.0 / COUNT(*),
            2
        ) AS fraud_percentage

    FROM claims

    GROUP BY
        Provider_Specialty,
        stay_bucket

)

SELECT

    Provider_Specialty,

    stay_bucket,

    total_claims,

    fraudulent_claims,

    fraud_percentage,

    RANK() OVER(
        PARTITION BY stay_bucket
        ORDER BY fraud_percentage DESC
    ) AS fraud_rank

FROM fraud_summary

ORDER BY
    stay_bucket,
    fraud_rank

""").fetchdf()

,Provider_Specialty,stay_bucket,total_claims,fraudulent_claims,fraud_percentage,fraud_rank
0,Radiology,Long Stay,255,42.0,16.47,1
1,Physical Therapy,Long Stay,267,40.0,14.98,2
2,Psychiatry,Long Stay,301,44.0,14.62,3
3,General Practice,Long Stay,289,42.0,14.53,4
4,Pediatrics,Long Stay,241,35.0,14.52,5
5,Oncology,Long Stay,275,39.0,14.18,6
6,Dermatology,Long Stay,282,38.0,13.48,7
7,Orthopedics,Long Stay,264,35.0,13.26,8
8,Neurology,Long Stay,288,37.0,12.85,9
9,Cardiology,Long Stay,265,28.0,10.57,10
10,General Practice,Medium Stay,38,8.0,21.05,1
11,Psychiatry,Medium Stay,43,7.0,16.28,2
12,Physical Therapy,Medium Stay,25,4.0,16.00,3
13,Pediatrics,Medium Stay,42,6.0,14.29,4
14,Orthopedics,Medium Stay,29,4.0,13.79,5
15,Radiology,Medium Stay,52,6.0,11.54,6
16,Oncology,Medium Stay,36,4.0,11.11,7
17,Cardiology,Medium Stay,36,4.0,11.11,7
18,Neurology,Medium Stay,46,5.0,10.87,9
19,Dermatology,Medium Stay,38,4.0,10.53,10
20,Cardiology,Short Stay,2496,1270.0,50.88,1
21,Orthopedics,Short Stay,2421,1200.0,49.57,2
22,General Practice,Short Stay,1438,264.0,18.36,3
23,Pediatrics,Short Stay,1490,270.0,18.12,4
24,Neurology,Short Stay,1533,275.0,17.94,5
25,Physical Therapy,Short Stay,1553,276.0,17.77,6
26,Oncology,Short Stay,1508,262.0,17.37,7
27,Psychiatry,Short Stay,1450,250.0,17.24,8
28,Dermatology,Short Stay,1513,254.0,16.79,9
29,Radiology,Short Stay,1586,258.0,16.27,10

In [23]:
con.execute("""

WITH fraud_summary AS (

    SELECT

        Provider_Specialty,

        CASE
            WHEN Length_of_Stay_Days <= 3 THEN 'Short Stay'
            WHEN Length_of_Stay_Days <= 10 THEN 'Medium Stay'
            ELSE 'Long Stay'
        END AS stay_bucket,

        COUNT(*) AS total_claims,

        SUM(
            CASE
                WHEN Is_Fraudulent = TRUE THEN 1
                ELSE 0
            END
        ) AS fraudulent_claims,

        ROUND(
            SUM(
                CASE
                    WHEN Is_Fraudulent = TRUE THEN 1
                    ELSE 0
                END
            ) * 100.0 / COUNT(*),
            2
        ) AS fraud_percentage

    FROM claims

    GROUP BY
        Provider_Specialty,
        stay_bucket

)

SELECT

    Provider_Specialty,

    stay_bucket,

    fraud_percentage,

    RANK() OVER(
        PARTITION BY stay_bucket
        ORDER BY fraud_percentage DESC
    ) AS rank_number,

    DENSE_RANK() OVER(
        PARTITION BY stay_bucket
        ORDER BY fraud_percentage DESC
    ) AS dense_rank_number,

    ROW_NUMBER() OVER(
        PARTITION BY stay_bucket
        ORDER BY fraud_percentage DESC
    ) AS row_number_value

FROM fraud_summary

ORDER BY
    stay_bucket,
    fraud_percentage DESC

""").fetchdf()

,Provider_Specialty,stay_bucket,fraud_percentage,rank_number,dense_rank_number,row_number_value
0,Radiology,Long Stay,16.47,1,1,1
1,Physical Therapy,Long Stay,14.98,2,2,2
2,Psychiatry,Long Stay,14.62,3,3,3
3,General Practice,Long Stay,14.53,4,4,4
4,Pediatrics,Long Stay,14.52,5,5,5
5,Oncology,Long Stay,14.18,6,6,6
6,Dermatology,Long Stay,13.48,7,7,7
7,Orthopedics,Long Stay,13.26,8,8,8
8,Neurology,Long Stay,12.85,9,9,9
9,Cardiology,Long Stay,10.57,10,10,10
10,General Practice,Medium Stay,21.05,1,1,1
11,Psychiatry,Medium Stay,16.28,2,2,2
12,Physical Therapy,Medium Stay,16.00,3,3,3
13,Pediatrics,Medium Stay,14.29,4,4,4
14,Orthopedics,Medium Stay,13.79,5,5,5
15,Radiology,Medium Stay,11.54,6,6,6
16,Oncology,Medium Stay,11.11,7,7,7
17,Cardiology,Medium Stay,11.11,7,7,8
18,Neurology,Medium Stay,10.87,9,8,9
19,Dermatology,Medium Stay,10.53,10,9,10
20,Cardiology,Short Stay,50.88,1,1,1
21,Orthopedics,Short Stay,49.57,2,2,2
22,General Practice,Short Stay,18.36,3,3,3
23,Pediatrics,Short Stay,18.12,4,4,4
24,Neurology,Short Stay,17.94,5,5,5
25,Physical Therapy,Short Stay,17.77,6,6,6
26,Oncology,Short Stay,17.37,7,7,7
27,Psychiatry,Short Stay,17.24,8,8,8
28,Dermatology,Short Stay,16.79,9,9,9
29,Radiology,Short Stay,16.27,10,10,10

In [24]:
con.execute("""

WITH monthly_fraud AS (

    SELECT

        DATE_TRUNC(
            'month',
            CAST(Claim_Date AS DATE)
        ) AS claim_month,

        COUNT(*) AS total_claims,

        SUM(
            CASE
                WHEN Is_Fraudulent = TRUE THEN 1
                ELSE 0
            END
        ) AS fraudulent_claims,

        ROUND(
            SUM(
                CASE
                    WHEN Is_Fraudulent = TRUE THEN 1
                    ELSE 0
                END
            ) * 100.0 / COUNT(*),
            2
        ) AS fraud_percentage

    FROM claims

    GROUP BY claim_month

)

SELECT *

FROM monthly_fraud

ORDER BY claim_month

""").fetchdf()

   claim_month  total_claims  fraudulent_claims  fraud_percentage
0   2020-01-01           289               87.0             30.10
1   2020-02-01           253               60.0             23.72
2   2020-03-01           286               73.0             25.52
3   2020-04-01           303               75.0             24.75
4   2020-05-01           318               93.0             29.25
..         ...           ...                ...               ...
62  2025-03-01           299               82.0             27.42
63  2025-04-01           269               66.0             24.54
64  2025-05-01           317               79.0             24.92
65  2025-06-01           312               86.0             27.56
66  2025-07-01           114               25.0             21.93

[67 rows x 4 columns]

In [25]:
con.execute("""

WITH monthly_fraud AS (

    SELECT

        DATE_TRUNC(
            'month',
            CAST(Claim_Date AS DATE)
        ) AS claim_month,

        COUNT(*) AS total_claims,

        SUM(
            CASE
                WHEN Is_Fraudulent = TRUE THEN 1
                ELSE 0
            END
        ) AS fraudulent_claims,

        ROUND(
            SUM(
                CASE
                    WHEN Is_Fraudulent = TRUE THEN 1
                    ELSE 0
                END
            ) * 100.0 / COUNT(*),
            2
        ) AS fraud_percentage

    FROM claims

    GROUP BY claim_month

)

SELECT

    claim_month,

    total_claims,

    fraudulent_claims,

    fraud_percentage,

    SUM(fraudulent_claims) OVER(
        ORDER BY claim_month
    ) AS cumulative_fraud_claims

FROM monthly_fraud

ORDER BY claim_month

""").fetchdf()

,claim_month,total_claims,fraudulent_claims,fraud_percentage,cumulative_fraud_claims
0,2020-01-01,289,87.0,30.10,87.0
1,2020-02-01,253,60.0,23.72,147.0
2,2020-03-01,286,73.0,25.52,220.0
3,2020-04-01,303,75.0,24.75,295.0
4,2020-05-01,318,93.0,29.25,388.0
...,...,...,...,...,...
62,2025-03-01,299,82.0,27.42,4755.0
63,2025-04-01,269,66.0,24.54,4821.0
64,2025-05-01,317,79.0,24.92,4900.0
65,2025-06-01,312,86.0,27.56,4986.0
66,2025-07-01,114,25.0,21.93,5011.0

In [26]:
con.execute("""

WITH monthly_fraud AS (

    SELECT

        DATE_TRUNC(
            'month',
            CAST(Claim_Date AS DATE)
        ) AS claim_month,

        SUM(
            CASE
                WHEN Is_Fraudulent = TRUE THEN 1
                ELSE 0
            END
        ) AS fraudulent_claims

    FROM claims

    GROUP BY claim_month

),

fraud_trend AS (

    SELECT

        claim_month,

        fraudulent_claims,

        LAG(fraudulent_claims) OVER(
            ORDER BY claim_month
        ) AS previous_month_fraud

    FROM monthly_fraud

)

SELECT

    claim_month,

    fraudulent_claims,

    previous_month_fraud,

    fraudulent_claims - previous_month_fraud
        AS fraud_change,

    ROUND(
        (
            (fraudulent_claims - previous_month_fraud)
            * 100.0
        ) / previous_month_fraud,
        2
    ) AS fraud_change_percentage

FROM fraud_trend

ORDER BY claim_month

""").fetchdf()

,claim_month,fraudulent_claims,previous_month_fraud,fraud_change,fraud_change_percentage
0,2020-01-01,87.0,NaN,NaN,NaN
1,2020-02-01,60.0,87.0,-27.0,-31.03
2,2020-03-01,73.0,60.0,13.0,21.67
3,2020-04-01,75.0,73.0,2.0,2.74
4,2020-05-01,93.0,75.0,18.0,24.00
...,...,...,...,...,...
62,2025-03-01,82.0,61.0,21.0,34.43
63,2025-04-01,66.0,82.0,-16.0,-19.51
64,2025-05-01,79.0,66.0,13.0,19.70
65,2025-06-01,86.0,79.0,7.0,8.86
66,2025-07-01,25.0,86.0,-61.0,-70.93

In [27]:
con.execute("""

WITH monthly_fraud AS (

    SELECT

        DATE_TRUNC(
            'month',
            CAST(Claim_Date AS DATE)
        ) AS claim_month,

        SUM(
            CASE
                WHEN Is_Fraudulent = TRUE THEN 1
                ELSE 0
            END
        ) AS fraudulent_claims

    FROM claims

    GROUP BY claim_month

)

SELECT

    claim_month,

    fraudulent_claims,

    ROUND(

        AVG(fraudulent_claims) OVER(

            ORDER BY claim_month

            ROWS BETWEEN 2 PRECEDING
            AND CURRENT ROW

        ),

        2

    ) AS moving_3_month_avg

FROM monthly_fraud

ORDER BY claim_month

""").fetchdf()

   claim_month  fraudulent_claims  moving_3_month_avg
0   2020-01-01               87.0               87.00
1   2020-02-01               60.0               73.50
2   2020-03-01               73.0               73.33
3   2020-04-01               75.0               69.33
4   2020-05-01               93.0               80.33
..         ...                ...                 ...
62  2025-03-01               82.0               70.67
63  2025-04-01               66.0               69.67
64  2025-05-01               79.0               75.67
65  2025-06-01               86.0               77.00
66  2025-07-01               25.0               63.33

[67 rows x 3 columns]

In [28]:
con.execute("""

WITH monthly_fraud AS (

    SELECT

        DATE_TRUNC(
            'month',
            CAST(Claim_Date AS DATE)
        ) AS claim_month,

        SUM(
            CASE
                WHEN Is_Fraudulent = TRUE THEN 1
                ELSE 0
            END
        ) AS fraudulent_claims

    FROM claims

    GROUP BY claim_month

)

SELECT

    claim_month,

    fraudulent_claims,

    LAG(fraudulent_claims) OVER(
        ORDER BY claim_month
    ) AS previous_month_fraud,

    LEAD(fraudulent_claims) OVER(
        ORDER BY claim_month
    ) AS next_month_fraud

FROM monthly_fraud

ORDER BY claim_month

""").fetchdf()

   claim_month  fraudulent_claims  previous_month_fraud  next_month_fraud
0   2020-01-01               87.0                   NaN              60.0
1   2020-02-01               60.0                  87.0              73.0
2   2020-03-01               73.0                  60.0              75.0
3   2020-04-01               75.0                  73.0              93.0
4   2020-05-01               93.0                  75.0              72.0
..         ...                ...                   ...               ...
62  2025-03-01               82.0                  61.0              66.0
63  2025-04-01               66.0                  82.0              79.0
64  2025-05-01               79.0                  66.0              86.0
65  2025-06-01               86.0                  79.0              25.0
66  2025-07-01               25.0                  86.0               NaN

[67 rows x 4 columns]

In [29]:
con.execute("""

SELECT

    Claim_ID,

    Provider_Specialty,

    Claim_Amount,

    Length_of_Stay_Days,

    Number_of_Previous_Claims_Patient,

    Claim_Submitted_Late,

    (

        CASE
            WHEN Claim_Submitted_Late = TRUE
            THEN 25
            ELSE 0
        END

        +

        CASE
            WHEN Length_of_Stay_Days <= 3
            THEN 20
            ELSE 0
        END

        +

        CASE
            WHEN Number_of_Previous_Claims_Patient >= 8
            THEN 15
            ELSE 0
        END

        +

        CASE
            WHEN Claim_Amount >= 1500000
            THEN 30
            ELSE 0
        END

    ) AS risk_score,

    Is_Fraudulent

FROM claims

ORDER BY risk_score DESC

LIMIT 50

""").fetchdf()

,Claim_ID,Provider_Specialty,Claim_Amount,Length_of_Stay_Days,Number_of_Previous_Claims_Patient,Claim_Submitted_Late,risk_score,Is_Fraudulent
0,8238,Physical Therapy,2318394.59,0,0,True,75,True
1,14702,Pediatrics,1685494.83,0,0,True,75,False
2,19763,Psychiatry,2256270.07,0,0,True,75,False
3,16220,Orthopedics,1999321.23,0,0,True,75,True
4,10984,Orthopedics,2080450.77,0,0,True,75,False
5,3058,Oncology,1653270.19,0,0,True,75,True
6,4574,General Practice,2454841.06,0,0,True,75,False
7,7753,Cardiology,1739818.82,0,0,True,75,False
8,2504,Radiology,2153091.05,0,0,True,75,True
9,1172,Radiology,2115732.35,3,0,True,75,True
10,19275,Radiology,2137646.98,1,0,True,75,False
11,8585,Oncology,2259820.12,0,0,True,75,True
12,3694,Neurology,2492320.67,0,0,True,75,False
13,4293,Radiology,1803609.96,0,0,True,75,False
14,7227,Dermatology,1912790.14,0,0,True,75,True
15,1871,Dermatology,1652911.28,0,0,True,75,False
16,15491,Dermatology,2288758.76,0,0,True,75,False
17,14502,Radiology,2421162.18,0,0,True,75,False
18,19554,General Practice,1888927.46,0,0,True,75,False
19,8903,Physical Therapy,2459770.71,0,0,True,75,False
20,7221,Cardiology,2110574.15,0,0,True,75,False
21,18590,General Practice,2496404.82,0,0,True,75,True
22,1988,Physical Therapy,1512200.29,0,0,True,75,False
23,18705,Psychiatry,2192431.02,0,0,True,75,False
24,2774,Psychiatry,2285735.34,0,0,True,75,True
25,687,Neurology,2072722.48,0,0,True,75,False
26,16253,General Practice,2392977.90,0,0,True,75,False
27,1920,Neurology,1500658.89,0,0,True,75,False
28,8776,General Practice,1975483.77,0,0,True,75,False
29,4960,Dermatology,1777817.45,0,0,True,75,False
30,15155,Physical Therapy,1963322.83,0,0,True,75,True
31,14109,General Practice,2235705.04,0,0,True,75,True
32,4690,Dermatology,2415347.75,0,0,True,75,False
33,10724,Neurology,1828173.17,0,0,True,75,True
34,18891,Physical Therapy,2359226.11,0,0,True,75,False
35,11460,Psychiatry,2499394.04,0,0,True,75,False
36,2936,Oncology,1520857.52,0,0,True,75,False
37,18138,Pediatrics,1994187.55,0,0,True,75,False
38,6704,Dermatology,2054714.22,0,0,True,75,False
39,17039,Pediatrics,2088293.84,0,0,True,75,False
40,12101,Psychiatry,2476890.75,0,0,True,75,True
41,14946,Orthopedics,1798634.91,0,0,True,75,False
42,6423,Radiology,1661622.83,0,0,True,75,True
43,17168,Cardiology,1818696.78,0,0,True,75,False
44,11690,Dermatology,1942296.77,0,0,True,75,False
45,9680,Neurology,1560469.06,0,0,True,75,False
46,6561,Oncology,2261734.67,0,0,True,75,True
47,11777,Pediatrics,2473391.25,0,0,True,75,False
48,11442,Cardiology,1622004.86,0,0,True,75,True
49,4672,Pediatrics,2393125.02,0,0,True,75,False

In [30]:
con.execute("""

WITH risk_scoring AS (

    SELECT

        Claim_ID,

        (

            CASE
                WHEN Claim_Submitted_Late = TRUE
                THEN 25
                ELSE 0
            END

            +

            CASE
                WHEN Length_of_Stay_Days <= 3
                THEN 20
                ELSE 0
            END

            +

            CASE
                WHEN Number_of_Previous_Claims_Patient >= 8
                THEN 15
                ELSE 0
            END

            +

            CASE
                WHEN Claim_Amount >= 1500000
                THEN 30
                ELSE 0
            END

        ) AS risk_score,

        Is_Fraudulent

    FROM claims

)

SELECT

    CASE

        WHEN risk_score >= 60
        THEN 'High Risk'

        WHEN risk_score >= 30
        THEN 'Medium Risk'

        ELSE 'Low Risk'

    END AS risk_segment,

    COUNT(*) AS total_claims,

    SUM(
        CASE
            WHEN Is_Fraudulent = TRUE
            THEN 1
            ELSE 0
        END
    ) AS fraudulent_claims,

    ROUND(

        SUM(
            CASE
                WHEN Is_Fraudulent = TRUE
                THEN 1
                ELSE 0
            END
        ) * 100.0 / COUNT(*),

        2

    ) AS fraud_percentage

FROM risk_scoring

GROUP BY risk_segment

ORDER BY fraud_percentage DESC

""").fetchdf()

  risk_segment  total_claims  fraudulent_claims  fraud_percentage
0  Medium Risk         10469             2805.0             26.79
1    High Risk          4112              955.0             23.22
2     Low Risk          5519             1251.0             22.67

In [31]:
con.execute("""

WITH claim_percentiles AS (

    SELECT

        Claim_ID,

        Provider_Specialty,

        Claim_Amount,

        Is_Fraudulent,

        NTILE(10) OVER(
            ORDER BY Claim_Amount DESC
        ) AS claim_decile

    FROM claims

)

SELECT

    claim_decile,

    COUNT(*) AS total_claims,

    ROUND(
        AVG(Claim_Amount),
        2
    ) AS avg_claim_amount,

    SUM(
        CASE
            WHEN Is_Fraudulent = TRUE
            THEN 1
            ELSE 0
        END
    ) AS fraudulent_claims,

    ROUND(

        SUM(
            CASE
                WHEN Is_Fraudulent = TRUE
                THEN 1
                ELSE 0
            END
        ) * 100.0 / COUNT(*),

        2

    ) AS fraud_percentage

FROM claim_percentiles

GROUP BY claim_decile

ORDER BY claim_decile

""").fetchdf()

,claim_decile,total_claims,avg_claim_amount,fraudulent_claims,fraud_percentage
0,1,2010,2368493.42,448.0,22.29
1,2,2010,2105271.83,429.0,21.34
2,3,2010,1837529.97,432.0,21.49
3,4,2010,1571047.76,490.0,24.38
4,5,2010,1332269.34,742.0,36.92
5,6,2010,1110227.06,719.0,35.77
6,7,2010,888009.19,680.0,33.83
7,8,2010,668085.61,688.0,34.23
8,9,2010,426228.27,264.0,13.13
9,10,2010,146327.87,119.0,5.92

In [32]:
con.execute("""

WITH yearly_cohorts AS (

    SELECT

        EXTRACT(
            YEAR FROM CAST(Claim_Date AS DATE)
        ) AS claim_year,

        Claim_Amount,

        Is_Fraudulent

    FROM claims

)

SELECT

    claim_year,

    COUNT(*) AS total_claims,

    ROUND(
        AVG(Claim_Amount),
        2
    ) AS avg_claim_amount,

    SUM(
        CASE
            WHEN Is_Fraudulent = TRUE
            THEN 1
            ELSE 0
        END
    ) AS fraudulent_claims,

    ROUND(

        SUM(
            CASE
                WHEN Is_Fraudulent = TRUE
                THEN 1
                ELSE 0
            END
        ) * 100.0 / COUNT(*),

        2

    ) AS fraud_percentage

FROM yearly_cohorts

GROUP BY claim_year

ORDER BY claim_year

""").fetchdf()

,claim_year,total_claims,avg_claim_amount,fraudulent_claims,fraud_percentage
0,2020,3652,1248869.28,936.0,25.63
1,2021,3630,1244523.66,903.0,24.88
2,2022,3674,1246048.77,921.0,25.07
3,2023,3694,1248640.88,923.0,24.99
4,2024,3589,1243322.48,860.0,23.96
5,2025,1861,1236043.57,468.0,25.15

In [33]:
con.execute("""

SELECT

    COUNT(*) AS total_claims,

    SUM(
        CASE
            WHEN Is_Fraudulent = TRUE
            THEN 1
            ELSE 0
        END
    ) AS fraudulent_claims,

    ROUND(

        SUM(
            CASE
                WHEN Is_Fraudulent = TRUE
                THEN 1
                ELSE 0
            END
        ) * 100.0 / COUNT(*),

        2

    ) AS fraud_percentage,

    ROUND(
        AVG(Claim_Amount),
        2
    ) AS avg_claim_amount,

    ROUND(
        SUM(Claim_Amount),
        2
    ) AS total_claim_amount,

    ROUND(

        AVG(
            CASE
                WHEN Is_Fraudulent = TRUE
                THEN Claim_Amount
            END
        ),

        2

    ) AS avg_fraudulent_claim_amount

FROM claims

""").fetchdf()

,total_claims,fraudulent_claims,fraud_percentage,avg_claim_amount,total_claim_amount,avg_fraudulent_claim_amount
0,20100,5011.0,24.93,1245349.03,2.503152e+10,1299777.4